<script type='application/ld+json'>
{ &quot;@context&quot;: &quot;http://schema.org&quot;, &quot;@type&quot;: &quot;BlogPosting&quot;, &quot;mainEntityOfPage&quot;: { &quot;@type&quot;: &quot;WebPage&quot;, &quot;@id&quot;: &quot;<data:post.url.canonical.jsonEscaped/>&quot; }, &quot;headline&quot;: &quot;<data:post.title.jsonEscaped/>&quot;, &quot;description&quot;: &quot;<data:post.snippets.short.jsonEscaped/>&quot;,
<b:if cond='data:view.isSingleItem'>&quot;articleBody&quot;: &quot;<b:eval expr='(data:post.body).jsonEscaped'/>&quot;,
</b:if> &quot;datePublished&quot;: &quot;<data:post.date.iso8601.jsonEscaped/>&quot;, &quot;dateModified&quot;: &quot;<data:post.lastUpdated.iso8601.jsonEscaped/>&quot;, &quot;image&quot;: { &quot;@type&quot;: &quot;ImageObject&quot;, 
&quot;url&quot;: &quot;<b:eval expr='(data:post.featuredImage ? resizeImage(data:post.featuredImage, 1280, &quot;1280:766&quot;) : &quot;https://1.bp.blogspot.com/-Sy_4X_mHQ8E/XRw1BMemCCI/AAAAAAAAEeE/Sv14v2reYhIm5X1lMXKEuhdkFGCAThelQCLcBGAs/s1600/no-image-thumbnail.png&quot;).jsonEscaped'/>&quot;,
&quot;height&quot;: 766, &quot;width&quot;: 1280 }, &quot;publisher&quot;: { &quot;@type&quot;: &quot;Organization&quot;, &quot;name&quot;: &quot;<data:blog.title/>&quot;, &quot;logo&quot;: { &quot;@type&quot;: &quot;ImageObject&quot;, 
&quot;url&quot;: &quot;https://1.bp.blogspot.com/-4fIz5S-Di_c/XRumS7B9JoI/AAAAAAAAEdo/n3gQfv3WmwMLE5fIfODvjud9iLyxa-AwQCLcBGAs/s600/LogoMahaTemplates.png&quot;, 
&quot;width&quot;: 600, &quot;height&quot;: 60 } }, &quot;author&quot;: { &quot;@type&quot;: &quot;Person&quot;, &quot;name&quot;: &quot;<data:post.author.name.jsonEscaped/>&quot;, &quot;url&quot;: &quot;<data:post.author.profileUrl.jsonEscaped/>&quot;, &quot;image&quot;: &quot;<data:post.author.authorPhoto.image.jsonEscaped/>&quot; } }
</script>
<script type='application/ld+json'>{ &quot;@context&quot;: &quot;https://schema.org&quot;, &quot;@type&quot;: &quot;WebSite&quot;, &quot;url&quot;: &quot;<data:blog.homepageUrl/>&quot;, &quot;potentialAction&quot;: { &quot;@type&quot;: &quot;SearchAction&quot;, &quot;target&quot;: &quot;<data:blog.homepageUrl/>search?q={search_term}&quot;, &quot;query-input&quot;: &quot;required name=search_term&quot; } }</script>
